version: '1.0'
services:
  backend:
   build: 
    context: .
    dockerfile: Dockerfile
    no_cache: true
   ports:
     - 3000:3000
   depends_on:
      - redis
   volumes:
      - dataContainer:/build
   networks:
      - network-nginx



  redis:
   image: 'redis:alpine'
   ports:
     - 50363:50363
   networks:
     - network-nginx
    
volumes:
  dataContainer:
    external: true

networks:
  network-nginx:
   driver: bridge
   ipam:
     driver: default
  